config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 
resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
 #validates :name, :presence =>true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
     @projects = Project.all
  end

  def new
     @project= Project.new
  end

  def create
	@project= Project.new(params[:project])
	@project.save
	flash[:notice]= "Project has been created."
	redirect_to @project
   end

  def show
	@project= Project.find(params[:id])
  end

  def edit
	@project= Project.find(params[:id])
  end
  
  def update
     @project = Project.find(params[:id])

     if @project.update_attributes(params[:project])
        flash[:notice]= "Project has been updated."
        redirect_to @project
      else
        flash[:alert]= "Project has not been updated."
        render :action => "edit" 
      end
  end

 def destroy
    @project= Project.find(params[:id])
    @project.destroy
    flash[:notice]= "Project has been deleted." 
    redirect_to projects_path 
  end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticketee</title>
    <%= csrf_meta_tags %>
  

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
   <% flash.each do |key, value| %>
	<divclass='flash'id='<%= key%>'>
		<%= value %>
	</div>
   <% end%
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <p>
      <%= f.label :name %>
       <%= f.text_field :name %>
   </p>
    <%= f.submit %> 
<% end%>

app/views/projects/edit.html.erb
<h2>Edit project</h2>
  <%=render"form" %>

app/views/projects/index.html.erb
<h2>Projects</h2>
<ul>
	<% @projects.each do |project|%>
		<li><%= link_to project.name,project %></li>
	<% end %>
</ul>

app/views/projects/new.html.erb
<h2>New project</h2>
<%= render "form" %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<%= link_to "Edit Project", edit_project_path(@project)%>
<%= link_to "Delete Project", @project,:method => :delete,
   :confirm => "Are you sure youwantto delete this project?" %>